### PR TITLE
CMake fixes

### PR DESCRIPTION
**Pull request by jtojnar**
Some fixes improving parity with Autotools, see https://github.com/gdraheim/zziplib/issues/86.

Downstream PR: https://github.com/NixOS/nixpkgs/pull/85147

### CODE REVIEW

**Comment by jtojnar** [comment]
Build failure looks unrelated.

**Comment by gdraheim** [comment]
CMake Error at zzip/CMakeLists.txt:218 (join_paths):
  Unknown CMake command "join_paths".

cmake version 3.10.2

**Comment by gdraheim** [comment]
oh my fault.

**Comment by jtojnar** [comment]
CMake is not really my strong suit so there might be some issues there. Not sure what happens if one tries to build just the subdirectory.

**Comment by gdraheim** [comment]
I am currently setting up some docker testbuilds, and I missed the new subdir.

That patches are great, thank you a lot.

**Pull request merged**
