### PR TITLE
Fix compilation on Mingw and recent compilers.

### PR DESCRIPTION
**Pull request by geromueller**

### CODE REVIEW

**Comment by gdraheim** [comment]
The problems have been solved with different code.

There had already been occurrence in write.c but those had been been generalized - there are now internal header files <zzip/__mkdir.h> and <zzip/__string.h> to handle the difference.

Since there is no specific test to mingw her it would be nice to check the master branch.

**Comment by geromueller** [comment]
Good, the code in master is much cleaner! EBADMSG is still not defined though. Maybe there is a central place for it aswell?

**Comment by gdraheim** [comment]
I had overlooked those patch lines .... a new zzip/__errno.h has been introduced now.

**Comment by geromueller** [comment]
thanks. looking good!

**Pull request closed without merging**
